In [6]:
import pandas as pd
from pandas_datareader import data
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.datasets import fetch_california_housing # Replaced load_boston
from sklearn.model_selection import GridSearchCV

In [7]:
# Load the California housing dataset
housing = fetch_california_housing()
df =pd.DataFrame(housing.data, columns=housing.feature_names)
df['MEDV'] = housing.target

In [8]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MEDV
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [9]:
X = df.iloc[:,0:8]
y = df.iloc[:,8]

In [10]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [11]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MEDV, Length: 20640, dtype: float64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   MEDV        20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [16]:
rt = DecisionTreeRegressor(criterion='friedman_mse', max_depth=5)

In [17]:
rt.fit(X_train, y_train)

DecisionTreeRegressor(criterion='friedman_mse', max_depth=5)

In [18]:
y_pred = rt.predict(X_test)

In [19]:
r2_score(y_test, y_pred)

0.5997321244428705

# **Hyperparameter Tuning**

In [24]:
param_grid = {
    'max_depth': [None, 5, 10, 15],
    'criterion': ['squared_error', 'friedman_mse', 'absolute_error'],
    'max_features' :[0.25,0.5,1],
    'min_samples_split': [2, 5, 10]
}

In [25]:
reg = GridSearchCV(DecisionTreeRegressor(), param_grid)

In [26]:
reg.fit(X_train, y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error'],
                         'max_depth': [None, 5, 10, 15],
                         'max_features': [0.25, 0.5, 1],
                         'min_samples_split': [2, 5, 10]})

In [28]:
reg.best_score_

np.float64(0.70525530732491)

In [29]:
reg.best_params_

{'criterion': 'squared_error',
 'max_depth': 10,
 'max_features': 0.5,
 'min_samples_split': 10}

# **Feature Importance**

In [30]:
for importance, name in sorted(zip(rt.feature_importances_, housing.feature_names), reverse=True):
    print(name, importance)

MedInc 0.7712117162048175
AveOccup 0.12840674614895556
HouseAge 0.04162087993608147
AveRooms 0.031260721268004645
Latitude 0.02204948028678216
Population 0.00248499828717747
Longitude 0.0020969502013717476
AveBedrms 0.000868507666809248